name: Travel Hacker - Test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Comprobar Python
        run: python --version

      - name: Ejecutar TravelHackerAI
        run: python src/main.py
